{"Subproblems": [{"Testcases": [{"status": 7, "Time": 0, "Memory": 0, "Input": "0\n0", "Answer": "0", "Output": "", "Description": "Traceback (most recent call last):\n  File \"/P1\", line 2, in <module>\n    print(num[0]+num[1])\nIndexError: list index out of range\n"}, {"status": 7, "Time": 0, "Memory": 0, "Input": "7\n8", "Answer": "15", "Output": "", "Description": "Traceback (most recent call last):\n  File \"/P1\", line 2, in <module>\n    print(num[0]+num[1])\nIndexError: list index out of range\n"}, {"status": 7, "Time": 0, "Memory": 0, "Input": "4\n3", "Answer": "7", "Output": "", "Description": "Traceback (most recent call last):\n  File \"/P1\", line 2, in <module>\n    print(num[0]+num[1])\nIndexError: list index out of range\n"}], "Debugger": true, "Score": 50, "GetScore": 0}, {"Testcases": [{"status": 7, "Time": 0, "Memory": 0, "Input": "0\n6", "Answer": "6", "Output": "", "Description": "Traceback (most recent call last):\n  File \"/P1\", line 2, in <module>\n    print(num[0]+num[1])\nIndexError: list index out of range\n"}, {"status": 7, "Time": 0, "Memory": 0, "Input": "7\n2", "Answer": "9", "Output": "", "Description": "Traceback (most recent call last):\n  File \"/P1\", line 2, in <module>\n    print(num[0]+num[1])\nIndexError: list index out of range\n"}, {"status": 7, "Time": 0, "Memory": 0, "Input": "4\n2", "Answer": "6", "Output": "", "Description": "Traceback (most recent call last):\n  File \"/P1\", line 2, in <module>\n    print(num[0]+num[1])\nIndexError: list index out of range\n"}], "Debugger": false, "Score": 50, "GetScore": 0}], "status": 11, "score": 0}